### ISSUE TITLE
Graph-level autoencoder

### ISSUE THREAD

**Issue by patrafter1999** [tkipf/gae#5]
Hi Kipf,

Thanks a lot for your excellent paper. I have two questions on GCNModelAE model.

1. InnerProductDecoder can be seen as an inverse operation of the encoder operation (GraphConvolutionSparse() followed by GraphConvolution()). It's like encoder/decoder architecture in sequence autoencoder, convolutional autoencoder, or stacked denoising autoencoder. However, InnerProductDecoder() inverses GraphConvolution() only while skipping the inverse of GraphConvolutionSparse() in order to get self.reconstructions. If you look at any typical autoencoder, the reconstruction is the same dimension as the original input (NxD; where N is the number of training samples and D is the feature vector size-1433 in cora dataset for instance). Your example doesn't seem to do this second inverse operation in decoder. Is it because your example code tries to auto-encode against 'node topology' (not against node features)?

2. Perhpas this question is related to my first question.
I'd like to cluster a list of graphs based on node features as well as graph topology. I thought this could be done using GCN-AE. If it's possible, how do you suggest to implement decoder and cost function?

Your answers would be greatly appreciated.

spark

**Comment by tkipf** [comment]
Hi, thanks for getting in touch. These are very good questions indeed.
1) In this work, we focused on auto-encoding the graph structure alone. We provide an option to condition the encoder on a set of node features. It is quite straightforward to extend this model to also decode node features or edge features (a simple MLP decoder will do in this case) - this could potentially improve predictive performance on a number of tasks.
2) If I understand correctly, you would like to learn latent representations of graphs instead of nodes and then cluster them. GAEs only support learning latent representations for nodes in a graph. Auto-encoding multiple graph instances comes with some difficulties. Since the set of nodes is unordered, reconstructing both nodes and edges from a fixed-size latent graph representation is challenging as it would involve evaluating all possible node orderings if done naively.

Hope this helps.

Thomas

**Comment by patrafter1999** [comment]
Thanks for your explanation, Kipf.
