### ISSUE TITLE
Why is roc computed using model.z_mean even in the VGAE case? 

### ISSUE THREAD

**Issue by danielegrattarola** [tkipf/gae#7]
Hi,
first of all, thanks for your work.
I'm looking at the code to understand the training process, but I can't understand why you used 
```
emb = sess.run(model.z_mean, feed_dict=feed_dict)
```
(line 107 in `train.py`) to compute the embeddings at test time for both models. 
Shouldn't the VGAE use `model.z` or am I missing something?
Also, why do you recompute the decoding manually, rather than using the model output directly?
I think one question will probably aswer the other, but I really can't see it. 

Thanks, 
Daniele

**Comment by tkipf** [comment]
Hi Daniele, thanks for your question! 

I agree with you that we should have taken a sample from the learned distribution over the latents (model.z) for a fully probabilistic model at test time. So it would probably have been better to sample and then take an expectation over the final ROC values. Since this is quite expensive to evaluate, we simply take the mean of the latents in this implementation (which is slightly different from taking the expectation after predicting links). This should probably also answer your second question.

If you find a significant difference in predictive scores between the two approaches, let me know!

**Comment by danielegrattarola** [comment]
>The correct way to do it, is to sample and then take an expectation over the predicted links.

You mean that you'd compute `adj_rec = np.dot(emb, emb.T)` (line 113) multiple times with different embeddings and then take the mean of the various `adj_rec`s?

Thanks again

**Comment by tkipf** [comment]
Yes, that’s what I meant

**Comment by danielegrattarola** [comment]
Beautiful, I get it now. 

Cheers!
